### ISSUE TITLE
False detections on Japanese hiragana, katakana and punctuations

### ISSUE THREAD

**Issue by peecky** [beaugunderson/emoji-aware#10]
require('emoji-aware').withoutEmoji('たまたま見つけたからといって、フォトジェニック。')
    // [ '見' ]

The sentence has no emojis, but most characters are detected as emojis.

**Comment by beaugunderson** [comment]
@peecky sorry! this is sloppiness on my part in defining the unicode range somewhere--i will track it down and add a test for it

**Comment by beaugunderson** [comment]
this specific issue is fixed in 3.0.4; let me know if you find others and i'll fix them :)

**Comment by peecky** [comment]
Thank you!
