### ISSUE TITLE
README contains misleading info on Lodash

### ISSUE THREAD

**Issue by jclem** [beaugunderson/emoji-aware#3]
The [README](https://github.com/beaugunderson/emoji-aware/blob/1fb595580be90fed42d875caa880b767546c815b/README.md) states that lodash's split function correctly splits strings containing emoji. However, the latest lodash release does not appear to do this:

<img width="475" alt="screenshot 2016-04-07 15 27 16" src="https://cloud.githubusercontent.com/assets/412282/14364080/3c0a2198-fcd5-11e5-8287-0588c3199b69.png">

**Comment by beaugunderson** [comment]
@jclem d'oh! i know @jdalton's goal is for lodash to [properly split emoji](https://github.com/lodash/lodash/releases/tag/4.0.0#Emojis); if you submit an issue there i'm sure it will get fixed (with bonus points for a failing test case) :)

**Comment by beaugunderson** [comment]
i'll also note that only lodash 4.x supports properly splitting emoji at this point, what version did you test with?

**Comment by jdalton** [comment]
LOL, I miss 1 function and all of the sudden it's lack of support. I'll fix it now. 

<img src="https://cloud.githubusercontent.com/assets/4303/14376327/70e0a372-fd1d-11e5-9240-f241c7b8a46d.png" height=30% width=30%>

What you're thinking of is `_.toArray`, which works. A string split will be difficult to get as it can split by regexp. I'll cover the case that's similar to `_.toArray` for now.

**Comment by jdalton** [comment]
What you're thinking of is `_.toArray` which works. A string split will be difficult to get as it can split by regexp. I'll cover the case that's similar to `_.toArray` for now.

**Comment by beaugunderson** [comment]
i appreciate you, @jdalton!

**Comment by jdalton** [comment]
Just bumped v4.9.0.

**Comment by beaugunderson** [comment]
(also this is totally my fault for erroneously referring to `split` in the README instead of `toArray`, sorry!)

**Comment by jclem** [comment]
Thanks for fixing @jdalton and @beaugunderson! Saved my day.
