### ISSUE TITLE
Extract emoji characters

### ISSUE THREAD

**Issue by danbovey** [beaugunderson/emoji-aware#6]
As [discussed here](https://twitter.com/notwaldorf/status/841773147296694272), there might be a use case in this library to add an `extract` function to get an array of only the emoji characters.

**Comment by beaugunderson** [comment]
the `onlyEmoji` and `withoutEmoji` functions already do this :)

**Comment by danbovey** [comment]
Ah wicked! You should add that to the README

**Comment by beaugunderson** [comment]
good call, README updated as well ✨
