### ISSUE TITLE
Combined Emojis Bug

### ISSUE THREAD

**Issue by joehiggs** [beaugunderson/emoji-aware#7]
How to reproduce:
onlyEmoji('[female weightlifter emoji with skintone]').length equals 2 when it should equal 1

**Comment by watzak** [comment]
Yes, unfortunately I also could reproduce it :(
Check this out 
👍🏿✌🏿️ => get false
👍🏿✌ => is ok

it's an issue with ✌🏿️ (jfyi)

**Comment by beaugunderson** [comment]
thank you both for reporting; this is fixed in 3.0.2. the underlying issue was that fitzpatrick modifiers can come before variation selectors (and not just after)
