### ISSUE TITLE
support for unicode 10.0

### ISSUE THREAD

**Issue by yairraz** [beaugunderson/emoji-aware#8]
Unicode 10.0 is coming soon (probably next month)
Does emoji-aware support this new update?

https://emojipedia.org/unicode-10.0/
http://unicode.org/versions/Unicode10.0.0/

**Comment by beaugunderson** [comment]
i don't think any of the new emoji are outside the currently parsed code ranges so yes, they're supported (and if you find any bugs open an issue and i'll get them fixed)
