### ISSUE TITLE
bug on flag

### ISSUE THREAD

**Issue by aminify** [beaugunderson/emoji-aware#9]
hi
your library doesn't work right with this flag emoji => 🏴󠁧󠁢󠁷󠁬󠁳󠁿
this is a rare emoji that contains 7 unicode code points and 14 code units in javascript string.
but unfortunately your library returns an array containing of 7 elements in this code snippet:
`> split('🏴󠁧󠁢󠁷󠁬󠁳󠁿 ')
//[ '🏴', '󠁧', '󠁢', '󠁷', '󠁬', '󠁳', '󠁿' ]`

**Comment by beaugunderson** [comment]
fixed in 3.0.4 (along with the english and scottish flags); sorry it took so long!
